version: "2"
services:
  mbt-feed-svc:
    image: "feeder"
    container_name: "feeder-srv"
    build:
      context: .
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./config:/config