feeder:
  version: "8"
  tg:
    token: "<token>"
    owner:
      id: "<id>"
      name: "<name>"
  stock:
    timeout: 10000
    schedule: "0 5 10,17 * * *"

spring:
  output:
    ansi:
      enabled: always

server:
  port: 9090