name: Gradle Build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test with Gradle
        run: ./gradlew clean test

      - name: Build Jar with Gradle
        run: ./gradlew feed-web:bootJar

      # - name: Generate config
      #  run: echo "${{ secrets.CONFIG_FILE }}" > src/config.js

      - name: Upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: feed-web.jar
          path: feeder-web/build/libs/feeder-web.jar